### PR TITLE
Wip master

### PR DESCRIPTION
**Pull request by alexanderGugel**
@thomastuts 

Hello Thomas!

So for this lab, I thought a little game might be quite entertaining and fun to play with (Tic Tac Toe).
It got a bit longer than expected, but I'm curious about your thoughts.

I'm planning on adding a couple more tests maybe, but I'm not too sure about how strict they should be in this case.

Anyways, let me know if you have any thoughts or if the general direction is ok.

Thanks so much!

### CODE REVIEW

**Comment by thomastuts** [comment]
This looks awesome! While it's certainly very challenging, I think this lab might be a little too extensive  — we generally reserve the super long labs until the end of a unit.

However, I think the core idea here is absolutely great. I feel like we can remove some of the fluff (like the `Field` component) and trim down in some other areas, but we should definitely use the tic-tac-toe as a base for the exercise. Awesome job! 💣 

Some consolidated remarks for this branch and the `wip-solution` branch in #2:
- The lab instructions could be a little more specific. This helps guide the students, as well as provide a more rigid platform to test (see https://github.com/learn-co-curriculum/react-props-lab/blob/b526f6a53941a31048602408ae462e67e8b825bf/README.md for an example of how I usually handle this stuff).
- Like I mentioned in other lessons, we only talk about pure components in a later unit. Can we refactor these components to ES2015 classes using only `render()`? I know it feels counterintuitive when you already know what pure components are, but for the purposes of teaching students React, we don't want to front-load too much of that stuff, we'll handle it in a later lesson.
- Is there a performance benefit (or other benefits) to using `static getInitialState()` over `this.state = ...` (in the constructor)? All React code I write uses `this.state = ...`, and pretty much all of the code I've seen in the wild also has this method of setting state.
- I think we can remove the checks for DOM classes, we're focused on the logic and component communication at the moment
- OTOH, it feels like we're missing some tests to test the actual functionality of the main `Game` component, e.g. testing the `handleClick()` method to ensure that the marker is played at the right spot, etc
- We need the `index-test.js` file as an entry file so we can bundle the tests for the browser. That bundling is done through `npm run bundle:test`, this should be done automatically on every Git commit — run `npm run copy-git-hooks` to add the Git hook if you don't have it in your repo yet. I _think_ we can just restore `index-test.js` and then require all of the other test files in that file, but I'm not sure. If you're running into any issues with this, let me know so we can figure out a solution.

Again, the core idea of this lab is incredibly good — it'll prove to be quite the challenge for the students, which is great 😄

**Comment by alexanderGugel** [comment]
> The lab instructions could be a little more specific. This helps guide the students, as well as provide a more rigid platform to test (see https://github.com/learn-co-curriculum/react-props-lab/blob/b526f6a53941a31048602408ae462e67e8b825bf/README.md for an example of how I usually handle this stuff).

Good point. Will do.

> Like I mentioned in other lessons, we only talk about pure components in a later unit. Can we refactor these components to ES2015 classes using only `render()`? I know it feels counterintuitive when you already know what pure components are, but for the purposes of teaching students React, we don't want to front-load too much of that stuff, we'll handle it in a later lesson.

Done. Sorry about that.

> Is there a performance benefit (or other benefits) to using `static getInitialState()` over `this.state = ...` (in the constructor)? All React code I write uses `this.state = ...`, and pretty much all of the code I've seen in the wild also has this method of setting state.

The game has a reset button. I think it makes sense to refactor this out into a (static) function, otherwise we would have to duplicate the initial state object. This is actually nicer in `React.createClass`, since you can just call `this.setState(this.getInitialState())`... that was kind of the idea. Definitely not a performance benefit, but even then, I don't think they should worry too much about performance of individual functions at this stage.

> I think we can remove the checks for DOM classes, we're focused on the logic and component communication at the moment

They are needed for making the game look like in the screenshot. Otherwise it would look a bit weird. We could also just add them beforehand in `wip-master`...

> OTOH, it feels like we're missing some tests to test the actual functionality of the main `Game` component, e.g. testing the `handleClick()` method to ensure that the marker is played at the right spot, etc

Done. Do we want some kind of complete intergration test as well? Currently everything is unit-tested, but we aren't actually mounting the component and "play" a real game...

> We need the `index-test.js` file as an entry file so we can bundle the tests for the browser. That bundling is done through `npm run bundle:test`, this should be done automatically on every Git commit 

Done.

> run `npm run copy-git-hooks` to add the Git hook if you don't have it in your repo yet. I _think_ we can just restore `index-test.js` and then require all of the other test files in that file, but I'm not sure. If you're running into any issues with this, let me know so we can figure out a solution.

Done.

**Comment by thomastuts** [comment]
> The game has a reset button. I think it makes sense to refactor this out into a (static) function, otherwise we would have to duplicate the initial state object. This is actually nicer in `React.createClass`, since you can just call `this.setState(this.getInitialState())`... that was kind of the idea. Definitely not a performance benefit, but even then, I don't think they should worry too much about performance of individual functions at this stage.

That makes sense. I wonder if it's easier if we define an `INITIAL_STATE` const that we can use to reset the state instead of using a static method on the class — I think it's a bit easier to understand, and students won't have learned about the `static` keyword (our usage of the ES2015 features is _fairly_ limited to not overburden them too much). What do you think?

> They are needed for making the game look like in the screenshot. Otherwise it would look a bit weird. We could also just add them beforehand in `wip-master`...

I think that might be a good idea. This lab is fairly extensive as-is, it might not be a good idea to give students more busywork by adding DOM classes, since we're focused on the React logic (for now, in final/bigger labs they should obviously do most of this stuff themselves).

> Done. Do we want some kind of complete intergration test as well? Currently everything is unit-tested, but we aren't actually mounting the component and "play" a real game...

The tests you've written so far seem to cover everything, they're super thorough and well thought-out! I don't think there's a need for integration testing at this point.

**Comment by alexanderGugel** [comment]
> That makes sense. I wonder if it's easier if we define an INITIAL_STATE const that we can use to reset the state instead of using a static method on the class — I think it's a bit easier to understand, and students won't have learned about the static keyword (our usage of the ES2015 features is fairly limited to not overburden them too much). What do you think?

Totally makes sense. Even if they decide to use `static` instead of the `const`, the tests would still pass. I changed the solution to use `INITIAL_STATE`.

**Comment by alexanderGugel** [comment]
Hello @thomastuts !

Any additional feedback for this or is this ready to merge / needs extra cleanup?

**Comment by thomastuts** [comment]
Hey @alexanderGugel, thanks for this. Really great stuff! I think the lesson is in a really good _state_ (drumroll) right now. Merged! 🎉

**Pull request merged**
